theme: jekyll-theme-slate
title: CPGE
permalink: /articles/:title

defaults:
  - scope:
      path: "assets/annal"
    values:
      annal: true  
  - scope:
      path: "assets/correction"
    values:
      correct: true    
  - scope:
      path: "assets/manual"
    values:
      manual: true
sass:
  sass_dir: _sass
