theme: jekyll-theme-slate
title: CPGE
permalink: /articles/:title

defaults:
  -  scope:
      path: "assets/pdf"
    values:
     annal: true
  -  scope:
      path: "assets/correction"
    values:
   correct: true
sass:
  sass_dir: _sass
